# PR0301: Lectura de datos de archivos

## Ingesta CSV

In [6]:
import pandas as pd

In [7]:
df_norte = pd.read_csv("ventas_norte.csv", sep=";")

df_norte = df_norte.rename(columns={
    'Fecha_Venta': 'fecha',
    'Nom_Producto': 'producto',
    'Cantidad_Vendida': 'cantidad',
    'Precio_Unit': 'precio_unitario'
})

df_norte['region'] = 'Norte'
df_norte.head()

   ID_Transaccion       fecha producto  cantidad  precio_unitario region
0            1000  2023-02-21   Laptop         4              423  Norte
1            1001  2023-01-15   Laptop         2              171  Norte
2            1002  2023-03-13   Laptop         3               73  Norte
3            1003  2023-03-02  Teclado         1              139  Norte
4            1004  2023-01-21  Monitor         4              692  Norte

## Ingesta Excel

In [8]:
df_sur_dict = pd.read_excel("ventas_sur.xlsx", sheet_name=None)
df_sur = pd.concat(df_sur_dict.values(), ignore_index=True)
df_sur = df_sur.rename(columns={
    'Date': 'fecha',
    'Item': 'producto',
    'Qty': 'cantidad',
    'UnitPrice': 'precio_unitario'
})
df_sur['region'] = 'Sur'
df_sur.head()

   SalesID      fecha producto  cantidad  precio_unitario region
0     2000 2023-03-01  Monitor         6              624    Sur
1     2001 2023-03-04   Laptop         7              941    Sur
2     2002 2023-03-26    Mouse         3              989    Sur
3     2003 2023-02-01   Webcam         3              621    Sur
4     2004 2023-03-28    Mouse         5              437    Sur

In [10]:
df2= pd.concat(
    df_ex.values(),
    ignore_index=True)
df2

NameError: name 'df_ex' is not defined

## Ingesta Json

In [ ]:
with open('ventas_este.json', 'r') as f:
    data_este = json.load(f)

df_este = pd.json_normalize(data_este, sep='_')
df_este = df_este.rename(columns={
    'timestamp': 'fecha',
    'detalles_producto_nombre': 'producto',
    'detalles_producto_specs_cantidad': 'cantidad',
    'detalles_producto_specs_precio': 'precio_unitario'
})
df_este['region'] = 'Este'
df_este.head()

,id_orden,fecha,producto,detalles_producto_categoria,cantidad,precio_unitario,cliente_nombre,cliente_email,region
0,ORD-3000,2023-03-09 00:00:00,Monitor,Electrónica,2,244,Cliente_0,cliente0@mail.com,Este
1,ORD-3001,2023-01-20 00:00:00,Laptop,Electrónica,2,578,Cliente_1,cliente1@mail.com,Este
2,ORD-3002,2023-01-01 00:00:00,Mouse,Electrónica,2,339,Cliente_2,cliente2@mail.com,Este
3,ORD-3003,2023-02-07 00:00:00,Webcam,Electrónica,2,158,Cliente_3,cliente3@mail.com,Este
4,ORD-3004,2023-03-18 00:00:00,Monitor,Electrónica,1,692,Cliente_4,cliente4@mail.com,Este

In [ ]:
columnas_estandar = ['fecha', 'producto', 'cantidad', 'precio_unitario', 'region']

df_total = pd.concat([
    df_norte[columnas_estandar], 
    df_sur[columnas_estandar], 
    df_este[columnas_estandar]
], ignore_index=True)

df_total.to_csv("ventas_consolidadas.csv", sep=",", encoding="utf-8", index=False)